name: Tags

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and upload zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Build
        run: |
          npm ci
          npm run lint-check
          npm run check
          npm run build
          npm run build-zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist-zip/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
